# F1/10 individual vehicle control parameters (copy as needed)
# Author: Varundev Suresh Babu
# Date: 06/21/2019

controller_manager:
  ros__parameters:
      update_rate: 10  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

ackermann_controller:
  ros__parameters:
    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    rear_wheels_names: [car_1_right_rear_wheel_joint, car_1_left_rear_wheel_joint]
    front_wheels_names: [car_1_right_front_wheel_joint, car_1_left_front_wheel_joint]

    wheelbase: 0.325
    front_wheel_track: 0.2
    rear_wheel_track: 0.2
    front_wheels_radius: 0.05
    rear_wheels_radius: 0.05

# left_rear_wheel_velocity_controller:
#   type: effort_controllers/JointVelocityController
#   joints:
#     - car_1_left_rear_wheel_joint
#   pid: { p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0 }

# right_rear_wheel_velocity_controller:
#   type: effort_controllers/JointVelocityController
#   dof_names:
#     - car_1_right_rear_wheel_joint
  
#   pid: { p: 1.0, i: 0.0, d: 0.0, i_clamp: 0.0 }

# left_front_wheel_velocity_controller:
#   type: effort_controllers/JointVelocityController
#   joints:
#     - car_1_left_front_wheel_joint
#   pid: { p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0 }

# right_front_wheel_velocity_controller:
#   type: effort_controllers/JointVelocityController
#   joints:
#     - car_1_right_front_wheel_joint
#   pid: { p: 0.5, i: 0.0, d: 0.0, i_clamp: 0.0 }

# left_steering_hinge_position_controller:
#   type: effort_controllers/JointPositionController
#   joints:
#     - car_1_left_steering_hinge_joint
#   pid: { p: 1.0, i: 0.0, d: 0.5 }

# right_steering_hinge_position_controller:
#   type: effort_controllers/JointPositionController
#   joints:
#     - car_1_right_steering_hinge_joint
#   pid: { p: 1.0, i: 0.0, d: 0.5 }