ekf_filter_node:
    ros__parameters:
      frequency: 30.0
      two_d_mode: true
      publish_acceleration: true
      publish_tf: true # be sure to set publish_tf to false in src/f1tenth_system/f1tenth_stack/config/vesc.yaml
      map_frame: map              # Defaults to "map" if unspecified
      odom_frame: odom            # Defaults to "odom" if unspecified
      base_link_frame: base_link  # Defaults to "base_link" ifunspecified
      world_frame: odom           # Defaults to the value ofodom_frame if unspecified

      # odom0: /mavros/wheel_odometry/odom
      # odom0_config: [true,  true,  false,
      #                 false, false, false,
      #                 true, true, false,
      #                 false, false, false,
      #                 false, false, false]

      imu0: /sensors/imu
      imu0_config: [false, false, false,
                    false, false, true,
                    false, false, false,
                    false, false, true,
                    true, false, false]
                    
      odom0: /odom
      odom0_config: [true, true, false,
                    false, false, true,
                    true, true, false,
                    false, false, true,
                    false, false, false]
